package:
  name: pyqtconfig
  version: "0.8.21"

source:
# this is used for build from git hub
  git_rev: 0.8.21
  git_url: https://github.com/mjirik/pyqtconfig.git

  # build:
  # noarch_python: True
#  ignore_prefix_files:
#    - devel
#    - examples

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pyqt
  run:
    - python
    - numpy
    - scipy
    - pyqt

test:
  imports:
    - pyqtconfig
about:
  home: https://github.com/mfitzp/pyqtconfig
  license: BSD License
  summary: 'An API for keeping PyQT widgets in sync with a config dictionary or QSettings objects'
#about:
#  home: https://github.com/mfitzp/pyqtconfig
#  license: BSD License
#  summary: 'An API for keeping PyQt widgets in sync with a config dictionary or QSettings object.'
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
